### ISSUE TITLE
Could not find module 'EsewaSDK' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by pharidali** [ayyshim/esewa_pnp#24]
Can you update this one ?

**Comment by ayyshim** [comment]
Please go through documentation https://github.com/ayyshim/esewa_pnp#how-to-install point 3rd.

**Comment by pharidali** [comment]
I don't know how to import that. 
Can you please help me?

**Comment by pharidali** [comment]
![Uploading Screen Shot 2021-05-05 at 11.27.27 PM.png…]()

**Comment by pharidali** [comment]
![Screen Shot 2021-05-05 at 11 27 27 PM](https://user-images.githubusercontent.com/24604834/117185519-a4e70e80-adf9-11eb-9b80-4fc5accae4a7.png)

**Comment by ayyshim** [comment]
```
dependencies:
  esewa_pnp:
    git:
      url: git://github.com/ayyshim/esewa_pnp.git
      ref: dev
```
