### ISSUE TITLE
xcode build fail

### ISSUE THREAD

**Issue by ThatRealGuy** [ayyshim/esewa_pnp#6]
Xcode's output:
↳
    <module-includes>:1:1: warning: umbrella header for module 'Flutter' does
    not include header 'FlutterNavigationController.h'
    #import "Headers/Flutter.h"
    ^
    SwiftEsewaPnpPlugin.swift:3:8: error: could not find module 'EsewaSDK' for
    target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios,
    arm64-apple-ios, arm, armv7
    import EsewaSDK
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by ayyshim** [comment]
esewa_pnp v.1.0.0 will compile fine if you run/test it on real physical device but to run/test it on iOS simulator you'll need to add esewa_pnp into your pubspec.yaml file in different way.

```yaml
dependencies:
  # esewa_pnp: ^1.0.0 # Use it on production app or while testing esewa_pnp on real physical iOS device.
  esewa_pnp:
      git: https://github.com/ayyshim/esewa_pnp.git
      ref: simulator
```

**Comment by ThatRealGuy** [comment]
I did try to force flutter to run it on device rather than using simulator

flutter run -d [device name]

**Comment by ayyshim** [comment]
**For physical device** add the plugin into your pubspec.yaml file like this

```yaml
dependencies:
  esewa_pnp: ^1.0.0
```

**For simulator** add the plugin into your pubspec.yaml file like this:
```yaml
dependencies:
  esewa_pnp:
      git: https://github.com/ayyshim/esewa_pnp.git
      ref: simulator
```

Don't forget to do `flutter clean` and `flutter pub get`
